version: '3.8'
services:
  dev-postgres:
    image: postgres:15
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: sendo
      POSTGRES_PASSWORD: wwwwwhpostgres
      POSTGRES_DB: 5w1h
    restart: always
    networks:
      - lesson
networks:
  lesson: